### ISSUE TITLE
Avaliar incorporação do livro de pré-cálculo da UFRGS

### ISSUE THREAD

**Issue by fgnievinski** [reamat/PreCalculo#16]
o livro de pré-cálculo da UFRGS foi recentemente disponibilizado na Internet:

http://hdl.handle.net/10183/212741

talvez ele poderia ser assimilado/incorporado ao presente projeto?

**Comment by he7d3r** [comment]
O rodapé do site indica que o material está sob a licença CC BY-**NC**-SA, que [é incompatível](https://wiki.creativecommons.org/wiki/Wiki/cc_license_compatibility#License_Compatibility_Chart) (por proibir o uso comercial).
Mesmo assim, imagino que o material pode ser consultado e adicionado às referências.
